import { Cookie } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Nav";

const kie = Cookie({
   subsets: ["latin"],
   weight:['400'] })

export const metadata = {
  title: "Fundamentals of React",
  description: "Generated by create next app",
  keywords: 'React,Next,Javascript,Tailwind, CSS, HTML'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kie.className} text-2xl`} >
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
